### Tek satır for döngüsü (One-liner for)

In [1]:
kelime = "Python"
harf_listesi = []

for harf in kelime:
    harf_listesi.append(harf)
    
print(harf_listesi)

['P', 'y', 't', 'h', 'o', 'n']


In [2]:
harf_listesi = [harf for harf in "Python"]
print(harf_listesi)

['P', 'y', 't', 'h', 'o', 'n']


### Tek satır if (One-liner if)

In [7]:
koşul = 3

if koşul > 5:
    kelime = "Elma"
elif koşul > 7:
    kelime = "Çilek"
else:
    kelime = "Armut"

In [8]:
kelime = "Elma" if koşul else "Armut" if koşul > 5 else "Çilek"

### Tek satır fonksiyon Lambda (One-liner function Lambda)

In [9]:
kare_al = lambda x: x**2
kare_al(5)

25

### map, reduce, filter, zip fonksiyonları

In [10]:
sayılar = [1, 2, 3, 4, 5, 6, 7]
sayıların_kareleri = []

for sayı in sayılar:
    sayıların_kareleri.append(kare_al(sayı))
print(sayıların_kareleri)

[1, 4, 9, 16, 25, 36, 49]


In [11]:
sayıların_kareleri =  map(kare_al, sayılar)
print(sayıların_kareleri)
for sayı in sayıların_kareleri:
    print(sayı)


1
4
9
16
25
36
49


In [12]:
from functools import reduce

sayılar = [1, 6, 3, 7, 10, 0]
print(reduce(lambda x,y: x if x > y else y, sayılar))

10


In [13]:
def beşten_uzun(kelime):
    if len(kelime) > 5:
        return True
    else:
        return False
isimler = ['Oğuz', 'Ahmet', 'Necati', 'Ali', 'Mehmet', 'Ziya']
uzun_isimler = filter(beşten_uzun, isimler)
print(uzun_isimler)
for isim in uzun_isimler:
    print(isim)

Necati
Mehmet


In [24]:
sayılar = [0, 1, 2, 3, 4, 5]
isimler = ['Oğuz', 'Ahmet', 'Necati', 'Ali', 'Mehmet', 'Ziya']


for i, j in zip(sayılar, isimler):
    print(str(i) + " " + j)


0 Oğuz
1 Ahmet
2 Necati
3 Ali
4 Mehmet
5 Ziya


### Assert anahtar kelimesi ( Assert keyword )

In [26]:
yaş = input("Yaşınız:")
assert int(yaş) >= 0, "Yaşınız negatif olamaz"

Yaşınız:-10


AssertionError: Yaşınız negatif olamaz

### Üreteçler (Generators)

In [27]:
def generator():
    i = 1
    print('Öncelikle bu basıldı')
    yield i

    i += 1
    print('Sonra bu')
    yield i

for eleman in generator():
    print("For döngüsü içinde:", eleman)
#print(next())

Öncelikle bu basıldı
For döngüsü içinde: 1
Sonra bu
For döngüsü içinde: 2


In [28]:
a = 5

def outer():
    a = 3
    def inner():
        nonlocal a
        a += 5
        print("inner fonksiyon:", a)
    print("outer fonksiyon:", a)
    return inner()

outer()
print("global:", a)

outer fonksiyon: 3
inner fonksiyon: 8
global: 5


### Decorators

In [29]:
from datetime import datetime

def show_time(func):
    def wrapper(name):
        print("Time:", datetime.now().time())
        func(name)
    return wrapper

@show_time
def say_hi(name="John"):
    print("Hi {}!".format(name))

say_hi("Ahmet")

Time: 11:58:05.387194
Hi Ahmet!


# Numpy

![Scalar Vector Matrix Tensor](https://res.cloudinary.com/practicaldev/image/fetch/s--oTgfo1EL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png)

In [30]:
import numpy as np

In [31]:
a = np.array([10, 20, 30, 40, 50, 60])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(6,)


In [32]:
type(a[3])

numpy.int32

In [33]:
a[2] *= 2
print(a[2])

60


In [34]:
a

array([10, 20, 60, 40, 50, 60])

In [35]:
b = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(b)
print(b.shape)
print(b.dtype)

[[10 20 30]
 [40 50 60]]
(2, 3)
int32


In [36]:
a = np.array([10, 20, 30, 40, 50, 60])
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.30481062])

In [37]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603,
       -0.95241298])

In [38]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301,
       4.09434456])

In [39]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21, 1.14200739e+26])

In [40]:
np.max(a)

60

In [41]:
np.min(a)

10

In [42]:
np.argmax(a)

5

In [43]:
np.mean(a)

35.0

In [44]:
np.median(a)

35.0

In [45]:
np.std(a)

17.07825127659933

In [46]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [47]:
# axis=1 => Row
# axis=0 => Column
np.sum(b, axis=0)

array([50, 70, 90])

In [48]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [49]:
ones = np.ones((3, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [50]:
full = np.full((3, 3), 5)
print(full)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [51]:
eye = np.eye(5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [52]:
arange = np.arange(7)
print(arange)

arange = np.arange(0, 10, 2)
print(arange)

[0 1 2 3 4 5 6]
[0 2 4 6 8]


In [53]:
# Create randint
random = np.random.random((3, 3))
print(random)

[[0.75045309 0.77975007 0.62905176]
 [0.91351339 0.52839272 0.70062118]
 [0.30267789 0.87445475 0.65003497]]


In [54]:
arr = np.random.randint(20, size=(5, 5))
print(arr)

[[ 5 15 18  0  9]
 [ 8  5 13 16  5]
 [16 15 16 17  0]
 [19 17 11  5 16]
 [ 1 11 10  5  1]]


In [55]:
zeros*6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
arr

array([[ 5, 15, 18,  0,  9],
       [ 8,  5, 13, 16,  5],
       [16, 15, 16, 17,  0],
       [19, 17, 11,  5, 16],
       [ 1, 11, 10,  5,  1]])

In [57]:
arr[0:3, ::]
#arr[satır, sütun]

array([[ 5, 15, 18,  0,  9],
       [ 8,  5, 13, 16,  5],
       [16, 15, 16, 17,  0]])

In [58]:
arr[arr > 10]

array([15, 18, 13, 16, 16, 15, 16, 17, 19, 17, 11, 16, 11])

In [59]:
np.where(arr > 10)

(array([0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4], dtype=int64),
 array([1, 2, 2, 3, 0, 1, 2, 3, 0, 1, 2, 4, 1], dtype=int64))

In [60]:
np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]).reshape(3, -1).shape

(3, 4)

In [61]:
c = np.random.randint(10, size=(3, 3))
print(c)
c_inv = np.linalg.inv(c)
print(c_inv)

[[2 6 2]
 [0 1 4]
 [6 5 7]]
[[-0.12264151 -0.30188679  0.20754717]
 [ 0.22641509  0.01886792 -0.0754717 ]
 [-0.05660377  0.24528302  0.01886792]]


## İç Çarpım (Dot product)
![Dot product](https://algebra1course.files.wordpress.com/2013/02/slide10.jpg)

credit: https://algebra1course.files.wordpress.com/

In [62]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a.shape)

(2, 3)


In [63]:
b = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
print(a.shape)

(2, 3)


In [65]:
# Transpose
(b.T).shape

(3, 2)

In [66]:
axb = np.dot(a, b.T)
print(axb)
print(axb.shape)

[[ 50  68]
 [122 167]]
(2, 2)
